config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root to: 'events#index'
resources :events
resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user, optional: true
	has_many :attendances
	has_many :users, through: :attendances
	validates :start_date, presence: true 
	validates :duration, presence: true
	validates :title, presence: true, length: { in: 5..140 }
	validates :description, presence: true, length: { in: 20..1000 }
	validates :price , presence: true, numericality: {less_than_or_equal_to: 1000}
	validates :location, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send
	has_many :attendances
	has_many :events

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@event = Event.all
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.create!(start_date:params[:start_date], duration: params[:duration], period: :morning) ,title: params[:title] , description:params[:description], price: params[:price],location: params[:location], user_id: current_user_id)
		@event.user = User.find_by(id: session[:user_id])
		flash[:notice]= "Bravo, vous avez créer un nouvel évènement!"
		redirect_to events_path
	end 

	def show
		@event = Event.find(params[:id])
		 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

  <title>Jumbotron Template for Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="jumbotron.css" rel="stylesheet">
</head>

<body>
  <main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3"> Ne ratez plus un seul event !</h1>
        <p> Inscrivez-vous vite pour pouvoir participer à tous les évènements près de chez vous mais aussi pour pouvoir organiser les v ! </p>
        <p><a class="btn btn-primary btn-lg" href="<%=new_user_registration_path%>" role="button">Inscrivez-vous! &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <% Event.all.each do |event| %>
        <div class="col-md-4">
          <h2><%= event.title %></h2>
          <p><%= event.description %> </p>
          <p><a class="btn btn-secondary" href="<%= event_path(event.id)%>" role="button">View details &raquo;</a></p>
          <br>
        </div>
        <% end %>
      </div>


      <hr>
    </div> <!-- /container -->


    <h2>Let's start !</h2>
    <ul>
      <% if user_signed_in? %>
      <li>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      </li>

      <li>
        Voici ton email : <%= current_user.email %>
      </li>

      <li>
        <%= link_to "Edit email / password", edit_user_registration_path %>
      </li>

      <% else %>
      <li>    
        <%= link_to "Sign in", new_user_session_path %>
      </li>

      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>

      <% end %>
    </ul>
  </main>
  <hr>
  <footer class="container">
    <p>&copy; Bénéstore</p>
  </footer>
    <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <script src="../../assets/js/vendor/popper.min.js"></script>
      <script src="../../dist/js/bootstrap.min.js"></script>
    </body>
    </html>

app/views/events/new.html.erb
<html>
<head>
	<title>Bienvenue sur Eventbride by THP</title>
</head>
<body>
	<h1>Créer ton event </h1><br>
	<%= form_for @event do |f| %> 
	<div class="form-group">
		<label>Titre de l'évènement</label>
		<%= f.text_field :title, class: 'form-control'%> 
	</div>
	<div class="form-group">
		<label>description de l'évènement</label>
		<%= f.text_area :description, class: 'form-control'%> 
	</div>
	<div class="form-group">
		<button type="submit", class="btn btn-primary">Créer le gossip</button>
	</div>
	<% end %>
</body>
</html>

app/views/events/show.html.erb
<html>
  <head>
    <title>Bienvenue sur Eventbride by THP</title>
  </head>
  <body>
    <h1>Evènement n°<%= @event.id %></h1><br>
   	<p><b>Titre de l'évènement : </b><%= @event.title %></p>
    <p><b>Description : </b><%= @event.description %></p>
    <button type="button" class="btn btn-outline-info"><a href="<%= events_path %>"> Revenir sur la page accueil</a></button>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventherokuapp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Eventbride by THP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Accueil <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_event_path %>">Créer un event</a>
        </li>
        <%if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="#">Ton profil</a>
        </li>
        <li class="nav-item">
          <ul class="nav-link"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></ul>
        </li>
        <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            S'inscrire / Se connecter
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="<%=new_user_registration_path%>">S'inscrire</a>
            <a class="dropdown-item" href="<%=new_user_session_path%>">Se connecter</a>
          </div>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container" style="padding-top: 5rem;">
    <% if flash[:notice]%>
    <div class="alert alert-success"><%= flash[:notice]%></dir>
      <%end%>
      <div class="container" style="padding-top: 5rem;">
        <% if flash[:danger]%>
        <div class="alert alert-danger"><%= flash[:danger]%></dir>
          <%end%>


  <%= yield %>
</body>
</html>